# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-16 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('tempat_tanggal_lahir', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=50)),
                ('alamat', models.TextField()),
                ('kelurahan', models.CharField(max_length=255)),
                ('no_hp', models.CharField(max_length=50)),
                ('instagram', models.CharField(max_length=255)),
                ('asal_sekolah', models.CharField(max_length=50)),
                ('kelas', models.CharField(max_length=10)),
                ('nama_orang_tua', models.CharField(max_length=50)),
                ('no_hp_orang_tua', models.CharField(max_length=50)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
