# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-16 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataform',
            name='gender',
        ),
        migrations.AddField(
            model_name='dataform',
            name='jenis_kelamin',
            field=models.CharField(default='jenis_kelamin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataform',
            name='perguruan_tinggi',
            field=models.TextField(default='perguruan_tinggi'),
            preserve_default=False,
        ),
    ]
